---
abstract: 'Scripts for the lazy programmer'
author:
  - 'Colin Newell, C<< <colin.newell at gmail.com> >>'
  - 'Colin Newell <colin.newell@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CodeHacks
no_index:
  directory:
    - inc
    - lib/auto
    - t
requires:
  File::ShareDir: 0
  File::Slurp: 0
  Modern::Perl: 0
  Template: 0
  YAML::Tiny: 0
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CodeHacks
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/colinnewell/CodeHacks.git
version: 0.01

